/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalRouteImport } from './routes/local'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineIndexRouteImport } from './routes/online/index'
import { Route as OnlineRoomIdRouteImport } from './routes/online/$roomId'

const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineIndexRoute = OnlineIndexRouteImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoomIdRoute = OnlineRoomIdRouteImport.update({
  id: '/online/$roomId',
  path: '/online/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/solo': typeof SoloRoute
  '/online/$roomId': typeof OnlineRoomIdRoute
  '/online': typeof OnlineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/solo': typeof SoloRoute
  '/online/$roomId': typeof OnlineRoomIdRoute
  '/online': typeof OnlineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/local': typeof LocalRoute
  '/login': typeof LoginRoute
  '/solo': typeof SoloRoute
  '/online/$roomId': typeof OnlineRoomIdRoute
  '/online/': typeof OnlineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/local'
    | '/login'
    | '/solo'
    | '/online/$roomId'
    | '/online'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/local'
    | '/login'
    | '/solo'
    | '/online/$roomId'
    | '/online'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/local'
    | '/login'
    | '/solo'
    | '/online/$roomId'
    | '/online/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LocalRoute: typeof LocalRoute
  LoginRoute: typeof LoginRoute
  SoloRoute: typeof SoloRoute
  OnlineRoomIdRoute: typeof OnlineRoomIdRoute
  OnlineIndexRoute: typeof OnlineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/': {
      id: '/online/'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/$roomId': {
      id: '/online/$roomId'
      path: '/online/$roomId'
      fullPath: '/online/$roomId'
      preLoaderRoute: typeof OnlineRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LocalRoute: LocalRoute,
  LoginRoute: LoginRoute,
  SoloRoute: SoloRoute,
  OnlineRoomIdRoute: OnlineRoomIdRoute,
  OnlineIndexRoute: OnlineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
